. .\LinkLocal.ps1
LinkLocal .anaconda
LinkLocal .conda
LinkLocal .dotnet
LinkLocal .ipython
LinkLocal .julia
LinkLocal .jupyter
LinkLocal .keras
LinkLocal .matplotlib
LinkLocal .nuget
LinkLocal .omnisharp
LinkLocal .pylint.d
LinkLocal .scripts
LinkLocal .seleniumwire
LinkLocal .ssh
LinkLocal .vscode
LinkLocal ansel
LinkLocal Desktop
LinkLocal Roaming
LinkLocal test.txt
LinkLocal WINDOWS